# Generated by Django 2.2.10 on 2020-04-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenderapp', '0002_auto_20200404_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='', max_length=60),
            preserve_default=False,
        ),
    ]
